---
default:
  interruptible: true

stages:
  - install
  - build
  - docs
  - publish

variables:
  NODE_VERSION: 22-alpine
  NODE_PACKAGE_MANAGER: pnpm
  SEMANTIC_RELEASE_WORKSPACE: 'true'

include:
  - project: devops/pipelines
    ref: node@2.0.0
    file:
      - /node/install.gitlab-ci.yml
      - /node/build.gitlab-ci.yml
      - /node/lint.gitlab-ci.yml

  - project: devops/pipelines
    ref: semantic-release@2.0.0
    file:
      - /semantic-release/publish.gitlab-ci.yml

install:
  stage: install
  extends: .node-install
  rules:
    - when: on_success

lint:
  stage: build
  extends: .node-lint
  rules:
    - when: on_success

build:
  stage: build
  extends: .node-build
  rules:
    - when: on_success

semantic-release:
  stage: publish
  extends: .semantic-release
  rules:
    - if: '$CI_COMMIT_REF_NAME =~ /^(master|main|alpha|beta|rc|next)$/'
      interruptible: true
    - when: never
