version: '3.7'
services:
  monorepo:
    image: cenk1cenk2/node-fnm:latest
    environment:
      SYNC_WAIT: 15
      PROXY_PACKAGES_FOLDER: packages
      SERVICE_0_CWD: packages/common
      SERVICE_0_NAME: common
      SERVICE_0_SYNC: 'true'
    volumes:
      - .:/data
